services:
  nginx:
    image: nginx:1.28.0
    restart: unless-stopped
    ports:
      - "7233:7233" # Temporal GRPC
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx

networks:
  nginx:
    name: nginx
    attachable: true
