services:
  grafana:
    image: grafana/grafana:12.0.2
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/provisioning/datasources/ds.yaml:/etc/grafana/provisioning/datasources/ds.yaml
    networks:
      grafana:
    deploy:
      mode: replicated
      replicas: ${GRAFANA_REPLICAS:-1}

  loki:
    image: grafana/loki:main-1b1e47f
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki/local-config.yaml:/etc/loki/local-config.yaml
    depends_on:
      - grafana
    networks:
      - grafana
    deploy:
      mode: replicated
      replicas: ${GRAFANA_REPLICAS:-1}

  promtail:
    image: grafana/promtail:main-1b1e47f
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - grafana
    deploy:
      mode: replicated
      replicas: ${GRAFANA_REPLICAS:-1}

networks:
  grafana: