services:
  traefik:
    image: traefik:v3.4.1
    command:
      - --api.insecure=true # Enable Traefik API directly on a path /api
      - --api.dashboard=true # Enable Traefik dashboard
      - --providers.swarm=true # Enable Docker Swarm in Traefik
      - --providers.swarm.exposedByDefault=false # Do not expose all Docker Swarm services
      - --providers.swarm.network=traefik
      - --entrypoints.web.address=:80 # Create an entrypoint "http" listening on address 80
    ports:
      - "80:80" # Traefik Web
      - "8080:8080" # Traefik Dashboard
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]

networks:
  traefik:
    name: traefik # Allow external containers to join the network
    attachable: true